export const skills = [
    // Frontend Development
    { category: "Frontend Development", name: "JavaScript", level: "Expert" },
    { category: "Frontend Development", name: "React", level: "Expert" },
    { category: "Frontend Development", name: "CSS", level: "Expert" },
    { category: "Frontend Development", name: "HTML", level: "Expert" },
    { category: "Frontend Development", name: "Responsive Web Design", level: "Expert" },
    { category: "Frontend Development", name: "Sass", level: "Expert" },
    { category: "Frontend Development", name: "React Hooks", level: "Advanced" },
    { category: "Frontend Development", name: "Redux", level: "Advanced" },
    { category: "Frontend Development", name: "TypeScript", level: "Advanced" },
    { category: "Frontend Development", name: "Material UI", level: "Advanced" },
    { category: "Frontend Development", name: "Prompt Engineering", level: "Advanced" },
    { category: "Frontend Development", name: "Astro", level: "Intermediate" },
    { category: "Frontend Development", name: "Next.js", level: "Intermediate" },
    { category: "Frontend Development", name: "Tailwind CSS", level: "Intermediate" },
    { category: "Frontend Development", name: "Web Vitals", level: "Intermediate" },
    { category: "Frontend Development", name: "Angular", level: "Novice" },
    { category: "Frontend Development", name: "React Native", level: "Novice" },
    { category: "Frontend Development", name: "Storybook", level: "Novice" },

    // Tools & DevOps
    { category: "Tools & DevOps", name: "Git", level: "Expert" },
    { category: "Tools & DevOps", name: "Docker", level: "Intermediate" },
    { category: "Tools & DevOps", name: "Kubernetes (k8s)", level: "Intermediate" },
    { category: "Tools & DevOps", name: "kubectl", level: "Advanced" },
    { category: "Tools & DevOps", name: "Phusion Passenger", level: "Advanced" },
    { category: "Tools & DevOps", name: "Elastic (Observability)", level: "Advanced" },
    { category: "Tools & DevOps", name: "New Relic", level: "Advanced" },
    { category: "Tools & DevOps", name: "Grafana", level: "Advanced" },
    { category: "Tools & DevOps", name: "Vite", level: "Intermediate" },
    { category: "Tools & DevOps", name: "Jest", level: "Intermediate" },
    { category: "Tools & DevOps", name: "Playwright - E2E Testing", level: "Novice" },

    // Backend & Databases
    { category: "Backend & Databases", name: "Node.js", level: "Intermediate" },
    { category: "Backend & Databases", name: "OAuth", level: "Intermediate" },
    { category: "Backend & Databases", name: "Firebase/Firestore", level: "Advanced" },
    { category: "Backend & Databases", name: "New Relic Query Language", level: "Advanced" },
    { category: "Backend & Databases", name: "Query DSL (Elasticsearch)", level: "Advanced" },
    { category: "Backend & Databases", name: "MongoDB", level: "Novice" },
    { category: "Backend & Databases", name: "PostgreSQL / pgAdmin", level: "Novice" },

    // Other Expertise
    { category: "Other Expertise", name: "A/B Testing", level: "Expert" },
    { category: "Other Expertise", name: "Collaborative", level: "Expert" },
    { category: "Other Expertise", name: "Slack", level: "Expert" },
    { category: "Other Expertise", name: "Trello", level: "Expert" },
    { category: "Other Expertise", name: "Jira", level: "Advanced" },
    { category: "Other Expertise", name: "Microsoft Teams", level: "Advanced" },
    { category: "Other Expertise", name: "Asana", level: "Intermediate" },
    { category: "Other Expertise", name: "ADA Compliance (a11y)", level: "Intermediate" },
    { category: "Other Expertise", name: "Cloudinary", level: "Advanced" },
    { category: "Other Expertise", name: "Video Editing", level: "Novice" },
];
